// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1uub-gH_a-bkP9ecMdbQGqDTlo2Uq-F0',
    appId: '1:380195206716:web:a056a05b17573bd722f539',
    messagingSenderId: '380195206716',
    projectId: 'gunita20-582d5',
    authDomain: 'gunita20-582d5.firebaseapp.com',
    storageBucket: 'gunita20-582d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbp6lNvZzREpnWPee5T_JbL9WrvmbBs2Y',
    appId: '1:380195206716:android:5539358c3b1ee3f322f539',
    messagingSenderId: '380195206716',
    projectId: 'gunita20-582d5',
    storageBucket: 'gunita20-582d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxcZGKGS890Qa9ogVy2MONVGUB1uu0thc',
    appId: '1:380195206716:ios:962395a64a1ca6db22f539',
    messagingSenderId: '380195206716',
    projectId: 'gunita20-582d5',
    storageBucket: 'gunita20-582d5.appspot.com',
    iosClientId: '380195206716-fn85gv0ddednnnga3gu9lpfcbpptc3t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
